"""Shared inputs for the Python/JS consistency test: (text, forbidden, stateful, sensitive_label) as the rules
should judge them. The unit test asserts Python against these; the Chrome test asserts the JS returns the same."""

TEXT_SAMPLES = [
    # navigation that only looks stateful: must stay allowed (tracking lookups are a core use case)
    ("包裹追蹤", False, False, False),
    ("追蹤查詢", False, False, False),
    ("e-book", False, False, False),
    ("Book now", False, True, False),
    ("加入追蹤", False, True, False),
    # english forbidden, word boundaries kept
    ("Pay now", True, False, False),
    ("pay", True, False, False),
    ("PAY NOW", True, False, False),
    ("payment history", False, False, False),
    ("PayPal", False, False, False),
    ("Repay", False, False, False),
    ("Pay-Per-View", True, False, False),
    ("Place order", True, False, False),
    ("Place  order", True, False, False),
    ("Place\torder", True, False, False),
    ("place orders", False, False, False),
    ("Buy Now!", True, False, False),
    ("Checkout", True, False, False),
    ("Log in", True, False, False),
    ("Login", True, False, False),
    ("Sign in", True, False, False),
    ("Sign up for news", True, False, False),
    ("Register", True, False, False),
    ("pay", True, False, False),
    ("ＰＡＹ ＮＯＷ", True, False, False),  # full-width letters fold under NFKC
    # chinese forbidden: normalized containment
    ("登入", True, False, False),
    ("會員登入", True, False, False),
    ("登 入", True, False, False),
    ("立即購買", True, False, False),
    ("前往結帳", True, False, False),
    ("確認訂購", True, False, False),
    ("註冊", True, False, False),
    ("查詢", False, False, False),
    ("開始查詢", False, False, False),
    ("下一頁", False, False, False),
    # stateful
    ("加入購物車", False, True, False),
    ("加入 購物車", False, True, False),
    ("Add to cart", False, True, False),
    ("add  to  bag", False, True, False),
    ("收藏", False, True, False),
    ("Subscribe", False, True, False),
    ("Follow us", False, False, False),
    ("Facebook", False, False, False),
    ("Book now", False, True, False),
    ("Delete", False, True, False),
    ("移除", False, True, False),
    ("刪除", False, True, False),
    ("預約", False, True, False),
    # sensitive labels
    ("密碼", False, False, True),
    ("Password", False, False, True),
    ("password:", False, False, True),
    ("Card number", False, False, True),
    ("卡號", False, False, True),
    ("CVV", False, False, True),
    ("OTP code", False, False, True),
    ("otpcode", False, False, False),
    ("驗證碼", False, False, True),
    ("身分證字號", False, False, True),
    ("Security code", False, False, True),
    ("", False, False, False),
    ("   ", False, False, False),
    # mixed: a phrase can be both forbidden and stateful-adjacent
    ("登入後加入購物車", True, True, False),
]

# (tag, input type, autocomplete, label, expected sensitive)
FIELD_SAMPLES = [
    ("INPUT", "password", "", "x", True),
    ("INPUT", "PASSWORD", "", "x", True),
    ("INPUT", "text", "cc-number", "x", True),
    ("INPUT", "text", "cc-exp-month", "x", True),
    ("INPUT", "text", "section-a cc-csc", "x", True),
    ("INPUT", "text", "one-time-code", "x", True),
    ("INPUT", "text", "current-password", "x", True),
    ("INPUT", "text", "new-password", "x", True),
    ("INPUT", "text", "cc-", "x", False),
    ("INPUT", "text", "username", "帳號", False),
    ("INPUT", "text", "", "密碼", True),
    ("INPUT", "text", "", "Card number", True),
    ("INPUT", "text", "", "暱稱", False),
    ("INPUT", "checkbox", "", "同意信用卡條款", False),
    ("INPUT", "submit", "", "密碼", False),
    ("TEXTAREA", "textarea", "", "OTP", True),
    ("SELECT", "select-one", "", "信用卡", False),
    ("BUTTON", "submit", "", "密碼", False),
]
